name: Run indexer
on:
  schedule:
    - cron: "15 */12 * * *"
  workflow_dispatch:

env:
  OUTPUT_PATH: ${{ github.workspace }}/output
  APP_PATH: ${{ github.workspace }}/src/ScoopSearch.Indexer.Console/
  GitHub__Token: ${{ secrets.GITHUB_TOKEN }}
  DOTNET_VERSION: '7.0.x'

jobs:
  main:
    name: Build and run indexer ⚙️️🚀🌐
    runs-on: ubuntu-latest

    steps:
      - name: Set branch-based environment variables
        uses: iamtheyammer/branch-env-vars@v1.2.1
        with:
          AzureSearch__ServiceUrl: |
            main:${{ vars.APPSETTINGS_AZURESEARCHSERVICEURL }}
            !default:${{ vars.APPSETTINGS_AZURESEARCHSERVICEURL_TESTS }}
          AzureSearch__IndexName: |
            main:${{ vars.APPSETTINGS_AZURESEARCHINDEXNAME }}
            !default:${{ vars.APPSETTINGS_AZURESEARCHINDEXNAME_TESTS }}
          AzureSearch__AdminApiKey: |
            main:${{ secrets.APPSETTINGS_AZURESEARCHADMINAPIKEY }}
            !default:${{ secrets.APPSETTINGS_AZURESEARCHADMINAPIKEY_TESTS }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore ${{ env.APP_PATH }}

      - name: Publish
        run: >
          dotnet publish ${{ env.APP_PATH }}
          --configuration Release
          --no-restore
          --output ${{ env.OUTPUT_PATH }}

      - name: Run indexer
        run: |
          cd ${{ env.OUTPUT_PATH }}
          ./ScoopSearch.Indexer.Console

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: ${{ env.OUTPUT_PATH }}/output.txt
